### ISSUE TITLE
Require is not defined

### ISSUE THREAD

**Issue by ghost** [lukeed/svelte-preprocess-esbuild#4]
Just out of curiosity, could this line: https://github.com/lukeed/svelte-preprocess-esbuild/blob/d73126e87a58d26aac9908346452360390979c97/src/index.ts#L131 be replaced with a dynamic import instead a `require()` without drastically affecting the code default behavior?

Correct me if i'm wrong, but by my experiences, making use of `require()`, directly forbids the use this library in a ES Modules scenario (either by putting `"type": "module"` on `package.json` or by running `.mjs` files),

Is it really required? or just a design choice?

**Comment by lukeed** [comment]
Are you actually getting an error thrown, or are you just asking for the sake of knowing?

Because I think if you're receiving an error, much/most of the Svelte toolchain itself isn't set up for ESM either.

**Comment by ghost** [comment]
I made some modifications that i believe led `svelte-preprocess-esbuild` to work with ESM, but i'm not 100% sure if it covers all the use cases as before, i tried to run the tests, but after tinkering a bit around the project, i could confirm that they were already failing before these changes, probably related to #1 

I published these changes on: https://github.com/henriquehbr/svelte-preprocess-esbuild
Here's a diff: https://github.com/lukeed/svelte-preprocess-esbuild/compare/master...henriquehbr:master

If you notice something wrong or out of place, just point it here and i'll sove it asap, in case these changes are good to go and don't break anything, i can submit a PR

**Comment by ryanatkn** [comment]
I can confirm both that `require` throws and the import is an error with ESM. Doing `import esbuild` works but `import * as esbuild` does not. (v0.8 and 0.9) (I had a [similar issue with `cheap-watch`](https://github.com/Conduitry/cheap-watch/pull/4))

Passing `tsconfigRaw` avoids the `require` code path btw.

update: esbuild 0.9 supports both import forms, so this will go away after upgrading. I must have made a mistake testing, and probably saw only the `require` error testing on the new version.

**Comment by lukeed** [comment]
I realized the issue here... derp 🤦 

You both must have been using native ESM, which follows the [`exports.import`](https://github.com/lukeed/svelte-preprocess-esbuild/blob/master/package.json#L26) file, which _incorrectly_ contains the `require` call.

I should remove that `import` entry & just ship `*.cjs` file to guarantee it always works. An `import` or `import()` to a CJS file/package will always be okay, but I'll test this locally to triple check.
